---
- name: Configure web server
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Create index.html file
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
            <title>Hello World</title>
          </head>
          <body>
            <h1>Hello World!</h1>
          </body>
          </html>

    - name: Install mod_ssl
      package:
        name: mod_ssl
        state: present

    - name: Ensure /etc/ssl/private directory exists
      file:
        path: /etc/ssl/private
        state: directory
        mode: '0700'

    - name: Create self-signed SSL certificate
      command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/selfsigned.key -out /etc/ssl/certs/selfsigned.crt -subj "/C=US/ST=State/L=City/O=Organization/CN=example.com"

    - name: Configure SSL for Apache
      copy:
        dest: /etc/httpd/conf.d/ssl.conf
        content: |
          Listen 443
          <VirtualHost *:443>
            ServerAdmin webmaster@example.com
            DocumentRoot /var/www/html
            SSLEngine on
            SSLCertificateFile /etc/ssl/certs/selfsigned.crt
            SSLCertificateKeyFile /etc/ssl/private/selfsigned.key
            ErrorLog logs/ssl_error_log
            CustomLog logs/ssl_access_log combined
          </VirtualHost>

    - name: Redirect HTTP to HTTPS
      lineinfile:
        path: /etc/httpd/conf.d/vhost.conf
        line: 'Redirect permanent / https://{{ ansible_default_ipv4.address }}/'
        create: yes

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

